### ISSUE TITLE
Use MobiMetadata.name if EXT header does not have title?

### ISSUE THREAD

**Issue by philippeitis** [wojciechkepka/mobi-rs#24]
During my testing, I noticed that a number of MOBI files didn't provide title records in the EXT header, but it seems like they provided a title via the name field. It seems like it might be a good idea for MobiMetadata::title() to return a copy of its name if the EXT header doesn't specifically provide its own title, as MobiMetadata doesn't return `exact` values in other cases either. We could also document this to prevent any confusion, and if someone needs the specific EXT field, they can get that manually.

**Comment by wojciechkepka** [comment]
I think it's a good idea so I went ahead and added it. I went with your suggestion and documented how the function behaves in case of missing EXTH header name value.
