### ISSUE TITLE
Provide struct which only reads headers / lazily parse records

### ISSUE THREAD

**Issue by philippeitis** [wojciechkepka/mobi-rs#9]
My use case for this library is essentially processing metadata, and importing books.

However, this library, by default, processes the records and stores a copy of the book in memory - this makes fetching metadata take 500x longer (0.0001s vs 0.05s), which is really noticable when adding 100+ books. There also isn't a way to access any of the headers by default, which means I would need to make a separate copy of the library with the desired edits.

I think offering three classes - Mobi for an entire book. MobiMetadata for all headers, and MobiRecord for records (or just Mobi / MobiMetadata) would make this library a lot more effective.

**Comment by wojciechkepka** [comment]
> However, this library, by default, processes the records and stores a copy of the book in memory - this makes fetching metadata take 500x longer (0.0001s vs 0.05s), which is really noticable when adding 100+ books.

I was thinking about the same thing recently, it's not very efficient to load it all into memory. That is definitely something I want to look into.

> There also isn't a way to access any of the headers by default, which means I would need to make a separate copy of the library with the desired edits.

I've opened an issue #10 for it.

> I think offering three classes - Mobi for an entire book. MobiMetadata for all headers, and MobiRecord for records (or just Mobi / MobiMetadata) would make this library a lot more effective.

That would definitely cleanup the public api, and would be more convenient to use. I would stick with Mobi/MobiMetadata/MobiRecord, but I will have to look into records with more detail.

**Comment by wojciechkepka** [comment]
So I've made some changes in #12 . I created a separate struct Metadata holding the headers and deleteder records field from Mobi so that it isn't processed on each instantiation. Right now to get the content the records are evaluated on each call but I think in the grand scheme of things it much better than it was previously.

Can you perhaps verify that current master branch works better when it comes to memory?

**Comment by philippeitis** [comment]
It does work better - however, my one issue is that opening a metadata object is a bit more inconvenient (no from_path), and it doesn't actually let me access the metadata (since all the functions for the specific fields are private to the crate). I personally would prefer either duplicating the metadata methods in Metadata and Mobi (so you could do `metadata.author()` or `mobi.author()`), or only having the metadata methods in Metadata (so you'd do `mobi.metadata.author()` and not `mobi.author()`).

As is, it's not possible to access the pub(crate) functions that Metadata's fields use (eg. I can't use `ExtHeader::get_record` since it's pub(crate). I also don't think making these functions pub is necessarily a  good idea either, since the metadata is located accross 4 fields and it may not be obvious to new users what field has which information - exposing a common interface is best. 

As such, I'm forced to use `Mobi`, so I'm still stuck with some memory overhead, which slows the code down by 25% (but this is still a lot better than the default of decompressing the records, which slows it down by 500x).

**Comment by wojciechkepka** [comment]
I've added the methods to Metadata in #15 for convienience. I don't think it will be so bad to have them duplicated on Mobi and Metadata. 

> As is, it's not possible to access the `pub(crate)` functions that Metadata's fields use (eg. I can't use `ExtHeader::get_record` since it's `pub(crate)`, and not `pub`). I also don't think making these functions `pub` is necessarily a good idea either

I actually hink this should stay this way. ExthHeader contains extra keys and they are on custom positions. Thats why I opted to just populate a hashmap of records and extract the popular ones like author, title... So that when someone wants to access this extra records he still can by using the public field `ExthHeader.records`.

**Comment by philippeitis** [comment]
That is what I meant, though I worded it poorly. The implementation looks great and performs excellently for me. However, from using other libraries, I get the impression that the name `Metadata` isn't specific enough, and can easily result in namespace collision. I feel like naming it `MobiMetadata` is appropriate, since other crates use a similar naming scheme - for instance, the epub crate uses `EpubArchive` and `EpubDoc` for its classes, and the zip crate uses `ZipArchive`, which I think works well.

**Comment by wojciechkepka** [comment]
At first I thought that Metadata was better, but you make a good point. Renamed it to MobiMetadata.

**Comment by wojciechkepka** [comment]
> As is, it's not possible to access the `pub(crate)` functions that Metadata's fields use (eg. I can't use `ExtHeader::get_record` since it's `pub(crate)`, and not `pub`). 

I've added some methods to `MobiMetadata` allowing extraction of exth records. So right now you can either do:
```rust
use mobi::{MobiMetadata, headers::ExthRecord};

let m = MobiMetadata::default();
let date = m.exth_record(ExthRecord::PublishDate);
// or lookup by position
date = m.exth_record_at(100);
```

I've added proper comments which discourage usage of those methods pointing potential users in the right direction.

So I guess most of the things listed in this issue are covered by #15
